# Name of your site (displayed in the header)
name: 부동산 정보 블로그

# Short bio or description (displayed in the header)
description: 부동산 관련 정보를 기록하고 공유합니다.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Your website URL, used for Sitemap.xml and your RSS feed
url: "https://nformation-ui.github.io"

# The baseurl is for projects hosted in subdirectories and should be empty
baseurl: ""

# Use the following plug-ins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
